GET http://localhost:3000/api/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YmRhOTVmZDg1NmM4YzQ3NDQ3ZTAxMiIsImVtYWlsIjoidGVzdHVzZXJAZXhhbXBsZS5jb20iLCJpYXQiOjE3NzQyNTUzMTQsImV4cCI6MTc3NDI1ODkxNH0.n8PTGdRIlwWxiTqRsl6zoywlhrXWjWJC4FhyIur2ND8

###
POST http://localhost:3000/api/accounts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YmRhOTVmZDg1NmM4YzQ3NDQ3ZTAxMiIsImVtYWlsIjoidGVzdHVzZXJAZXhhbXBsZS5jb20iLCJpYXQiOjE3NzQyNTUzMTQsImV4cCI6MTc3NDI1ODkxNH0.n8PTGdRIlwWxiTqRsl6zoywlhrXWjWJC4FhyIur2ND8

{
  "name": "Test Account",
  "type": "savings",
  "balance": 1000,
  "currency": "69bd18c9d177f9dff28563b1"
}

###

GET http://localhost:3000/api/accounts/69c061df50c0ddd32ae05bb7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YmRhOTVmZDg1NmM4YzQ3NDQ3ZTAxMiIsImVtYWlsIjoidGVzdHVzZXJAZXhhbXBsZS5jb20iLCJpYXQiOjE3NzQyNTUzMTQsImV4cCI6MTc3NDI1ODkxNH0.n8PTGdRIlwWxiTqRsl6zoywlhrXWjWJC4FhyIur2ND8

###
PUT http://localhost:3000/api/accounts/69c061df50c0ddd32ae05bb7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YmRhOTVmZDg1NmM4YzQ3NDQ3ZTAxMiIsImVtYWlsIjoidGVzdHVzZXJAZXhhbXBsZS5jb20iLCJpYXQiOjE3NzQyNTUzMTQsImV4cCI6MTc3NDI1ODkxNH0.n8PTGdRIlwWxiTqRsl6zoywlhrXWjWJC4FhyIur2ND8

{
  "name": "Updated Test Account",
  "type": "checking",
  "balance": 3000
}

###
DELETE http://localhost:3000/api/accounts/69c061df50c0ddd32ae05bb7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YmRhOTVmZDg1NmM4YzQ3NDQ3ZTAxMiIsImVtYWlsIjoidGVzdHVzZXJAZXhhbXBsZS5jb20iLCJpYXQiOjE3NzQyNTUzMTQsImV4cCI6MTc3NDI1ODkxNH0.n8PTGdRIlwWxiTqRsl6zoywlhrXWjWJC4FhyIur2ND8